spring.application.name=backend-vuln
spring.profiles.active=local

# PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=security-platform-springboot

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/pi2_logs
